diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50
  velocity_rolling_window_size: 2
  enable_odom_tf: true
  wheel_separation: 0.5
  wheel_radius: 0.075
  cmd_vel_timeout: 0.5
  publish_cmd: true
  allow_multiple_cmd_vel_publishers: false

  left_wheel: 
    - "L_wheel_joint"
  right_wheel: 
    - "R_wheel_joint"